import time
start = '''You're sitting in your dorm room at college, wondering about a dillema. Do you go to the party tonight, or do you study for your huge math test tomorrow?'''

print(start)

time.sleep(1)
print("Type 'study' to stay home and study or 'party' to go to the party.")
user_input = input()
if user_input == "study":
    print("You decide to stay home and study, and...")
    time.sleep(1)
    print("You got an A on your test!")
    time.sleep(1)
    print("But...")
    time.sleep(1)
    print("The captain of the football team comes up to you. He calls you a loser for not going to the party. Do you kick him or run away and cry?")
    time.sleep(2)
    print("Type 'kick' to kick him or 'cry' to run away and cry.")
    user_input = input()
    if user_input == "kick":
        print("You kick the bully! He shouts in pain, and he screams profanities at you.")
        time.sleep(1)
        print("Angry, you storm off. For once in your life, you were too preoccupied to look both ways while crossing the street.")
        time.sleep(2)
        print("CRASH. You were hit by a car.")
        time.sleep(1)
        print("GAME OVER.")

    elif user_input == "cry":
        print("You decide to turn and run away, avoiding confrontation.")
        time.sleep(1)
        print("You don't notice that someone is following you...")
        time.sleep(1)
        print("You stop at the end of a hallway you've never been down before.")
        time.sleep(1)
        print("Turning around, you finally notice someone chasing after you.")
        time.sleep(1)
        print("It takes you a second to recognize them.")
        time.sleep(1)
        print("It's the captain of the Math Team!")
        time.sleep(1)
        print("You wonder why he is following you.")
        time.sleep(1)
        print("He calls out your name.")
        time.sleep(1)
        print("Do you stop and wait for him to catch up or run away further down the unknown hallway?")
        time.sleep(2)
        print("Type 'wait' or 'run'.")
        user_input = input()
        if user_input == "wait":
            print("You stop, waiting for the guy to catch up.")
            time.sleep(1)
            print("He stops in front of you, leaning against the wall to catch his breath.")
            time.sleep(1)
            print("You notice that his glasses are fogging up.")
            time.sleep(1)
            print("'You run pretty fast, don't you?'")
            time.sleep(1)
            print("Do you say 'Who are you?' or stare at him blankly?")
            time.sleep(1)
            print("Type 'say' or 'stare'.")
            user_input = input()
            if user_input == "say":
                print("You ask him who he is.")

            elif user_input = input()
                print("You stare at him, hoping he will say something else.")
                time.sleep(1)
                print("'I'm sorry, did I scare you?'")
                time.sleep(1)
                print("You respond ")

        elif user_input == "run":
            print("You quickly turn back around, scared, and run away from him.")
            time.sleep(1)
            print("Which way should you turn?")
            time.sleep(1)
            print("Type 'right' or 'left'.")
            user_input = input()
            if user_input = "right":
                print("You turn right, and you reach the end of a different hallway.")
                time.sleep(1)
                print("Looking up, you realize that you are right outside of your English classroom.")
                time.sleep(1)
                print("You know where you are! You decide to head back to your dorm.")
                time.sleep(1)
                print("...")
                time.sleep(1)
                print("...")
                time.sleep(1)
                print("...")
                time.sleep(1)
                print("The next day, you run into the guy who was following you yesterday.")
                time.sleep(1)
                print("You try to hide so he won't see you, but it doesn't work.")
                time.sleep(1)
                print("'Hi, I'm sorry about yesterday.'")
                time.sleep(1)
                print("")

            elif user_input = "left":
                print("")

elif user_input == "party":
    print("You choose to go to the party, and ...")
    time.sleep(1)
    print("Almost immediately, someone comes up to you and asks if you want a drink. Should you?")
    time.sleep(1)
    print("Type 'yes' to drink or type 'no' to not drink.")
    if user_input == "yes":
        print("You decide to say yes! You are handed a beer, and you drink the night away.")
        time.sleep(1)
        print("...")
        time.sleep(1)
        print("...")
        time.sleep(1)
        print("...")
        time.sleep(1)
        print("Two weeks later")
        time.sleep(1)
        print("You discover that you're pregnant! You think back to the party you went to, and everything that you did...")
        time.sleep(1)
        print("You start thinking about how difficult it is to raise a baby while in school. Should you drop out of college?")
        time.sleep(1)
        print("Type 'yes' to drop out or type 'no' to stay in school.")
        user_input = input()
        if user_input == "yes":
            print("You drop out of college.")
            time.sleep(1)
            print("Sadly, without a college degree, you were unable to find a good job to support your child.")
            time.sleep(2)
            print("GAME OVER")

        elif user_input == "no":
            print("You stayed in school!")
            time.sleep(1)
            print("You got a college degree, and a good job.")
            time.sleep(1)
            print("You and your child now live in a nice house together.")
            time.sleep(1)
            print("AND YOU LIVED HAPPILY EVER AFTER")

    elif user_input == "no":
        print("You decide not to drink.")
