dogs = ["French Bulldog", #small
"Beagle",
"Yorkshire Terrier",
"Dachshund",
"Pembroke Welsh Corgi",
"Miniature Schnauzer",
"Cavalier King Charles Spaniel",
"Shih Tzu",
"Boston Terrier",
"Pomeranian",
"Havanese",
"Shetland Sheepdog",
"Pug",
"Chihuahua",
"Maltese",
"West Highland White Terrier",
"Bichon Frise",
"Papillon",
"Scottish Terrier",
"Cardigan Welsh Corgi",
"Cairn Terrier",
"Miniature Pinscher",
"Italian Greyhound",
"Lhasa Apso",
"Jack Russell Terrier",
"Chinese Crested",
"Coton De Tulear",
"Keeshond",
"Pekingese",
"Border Terrier",
"Brussels Griffon",
"Rat Terrier",
"Norwich Terrier",
"Silky Terrier",
"Japanese Chin",
"Welsh Terrier",
"Schipperke",
"Toy Fox Terrier",
"Irish Terrier",
"Miniature Bull Terrier",
"American Eskimo Dog",
"Parson Russell Terrier",
"Tibetan Spaniel",
"Smooth Fox Terrier",
"American Hairless Terrier",
"Norfolk Terrier",
"English Toy Spaniel",
"Manchester Terrier",
"Australian Terrier",
"Lakeland Terrier",
"Xoloitzcuintli",
"Affenpinscher",
"Swedish Vallhund",
"Sealyham Terrier",
"Bedlington Terrier",
"Glen of Imaal Terrier",
"Petit Basset Griffon Vendeen",
"Sussex Spaniel",
"Lowchen",
"Skye Terrier",
"Dandie Dinmont Terrier",
"Cesky Terrier",
"Norwegian Lundehund",
"Miniature Poodle",
"Toy Poodle",
"Miniature Shar Pei",
"Basset Bleu de Gascogne",
"Basset Fauve de Bretagne",
"Brazilian Terrier",
"Cockapoo",
"Danish-Swedish Farmdog",
"Drever",
"Dutch Smoushond",
"Jagdterrier",
"Goldendoodle",
"Japanese Spitz",
"Japanese Terrier",
"Lancashire Heeler",
"Miniature Bulldog",
"Patterdale Terrier",
"Plummer Terrier",
"Prazsky Krysarik",
"Russian Spaniel",
"Russian Toy",
"Karst Shepherd",
"Volpino Italiano",
"Alopekis",
"Basset Artesien Normand",
"Beaglier",
"Bolognese dog",
"Mountain Feist",
"Chizer",
"Cotonese",
"Taco Terrier",
"Cairmal",
"Kyi-Leo",
"Chorkie",
"Dorgi",
"Dorkie",
"Lucas Terrier",
"Mal-Shi",
"Shichon",
"Puggle",
"Russian Tsvetnaya Bolonka",
"Labrador Retriever", #medium
"Bulldog",
"Poodle",
"Boxer",
"Siberian Husky",
"Australian Shepherd",
"Brittany",
"English Springer Spaniel",
"American Cocker Spaniel",
"Vizsla",
"Weimaraner",
"Miniature American Shepherd",
"Border Collie",
"Basset Hound",
"Belgian Malinois",
"Shiba Inu",
"Soft Coated Wheaten Terrier",
"English Cocker Spaniel",
"Portuguese Water Dog",
"Airedale Terrier",
"Australian Cattle Dog",
"Samoyed",
"Bull Terrier",
"Whippet",
"German Wirehaired Pointer",
"Shar-Pei",
"Wirehaired Pointing Griffon",
"Chow Chow",
"Staffordshire Bull Terrier",
"American Staffordshire Terrier",
"Basenji",
"Nova Scotia Duck Tolling Retriever",
"Standard Schnauzer",
"Norwegian Elkhound",
"Boykin Spaniel",
"Wire Fox Terrier",
"Tibetan Terrier",
"Belgian Tervuren",
"Pointer",
"Lagotto Romagnolo",
"American Eskimo Dog",
"Bearded Collie",
"Kerry Blue Terrier",
"Treeing Walker Coonhound",
"Welsh Springer Spaniel",
"German Pinscher",
"Redbone Coonhound",
"Clumber Spaniel",
"Puli",
"Icelandic Sheepdog",
"Field Spaniel",
"Berger Picard",
"Spanish Water Dog",
"Entlebucher Mountain Dog",
"Wirehaired Vizsla",
"Portuguese Podengo Pequeno",
"Irish Water Spaniel",
"Plott Hound",
"American Water Spaniel",
"Norwegian Buhund",
"Finnish Lapphund",
"Pharaoh Hound",
"Canaan Dog",
"Polish Lowland Sheepdog",
"Finnish Spitz",
"American English Coonhound",
"Pyrenean Shepherd",
"Harrier",
"Cirneco dell’Etna",
"English Foxhound",
"Africanis",
"Aidi",
"Alaskan Klee Kai",
"American Pit Bull Terrier",
"American White Shepherd",
"Appenzeller Sennenhund",
"Ariegeois",
"Australian Bulldog",
"Australian Kelpie",
"Australian Stumpy Tail Cattle Dog",
"Austrian Black and Tan Hound",
"Austrian Pinscher",
"Barbet",
"Bavarian Mountain Hound",
"Belgian Shepherd Laekenois",
"Black Mouth Cur",
"Black Norwegian Elkhound",
"Blue Lacy",
"Bohemian Shepherd",
"Bouvier des Ardennes",
"Braque du Bourbonnais",
"Briquet Griffon Vendeen",
"Cão da Serra de Aires",
"Carolina Dog",
"Catahoula Bulldog",
"Catahoula Leopard Dog",
"Catalan Sheepdog",
"Cesky Fousek",
"Croatian Sheepdog",
"Deutsche Bracke",
"Dingo",
"Drentse Patrijshond",
"Dunker",
"English Shepherd",
"Eurasier",
"Fila Brasileiro",
"Finnish Hound",
"French Spaniel",
"Polish Hunting Dog",
"Grand Basset Griffon Vendeen",
"Griffon bleu de Gascogne",
"Hamilton Hound",
"Hokkaido Dog",
"Hovawart",
"Jämthund",
"Korean Jindo",
"Karelian Bear Dog",
"Kishu Ken",
"Kooikerhondje",
"Koolie",
"Kromfohrlander",
"Lapponian Herder",
"McNab",
"Mudi",
"Small Munsterlander",
"New Guinea Singing Dog",
"Norrbottenspets",
"Olde English Bulldogge",
"Perro de Presa Mallorquin",
"Peruvian Inca Orchid",
"Portuguese Pointer",
"Rafeiro do Alentejo",
"Sapsali",
"Sarplaninac",
"Schapendoes",
"Seppala Siberian Sleddog",
"Shikoku dog",
"Silken Windhound",
"Smaland Hound",
"Pont-Audemer Spaniel",
"Serbian Hound",
"Swedish Lapphund",
"Thai Bangkaew Dog",
"Thai Ridgeback",
"Transylvanian Hound",
"Wetterhoun",
"Andalusian Hound",
"Beagle-Harrier",
"Beaglier",
"Texas Heeler",
"Chippiparai",
"Cockalier",
"Double Doodle",
"Lurcher",
"Stabyhoun",
"German Shepherd", #large
"Golden Retriever",
"Rottweiler",
"German Shorthaired Pointer",
"Doberman Pinscher",
"Bernese Mountain Dog",
"Cane Corso",
"Collie",
"Rhodesian Ridgeback",
"Chesapeake Bay Retriever",
"Akita",
"Bloodhound",
"Bullmastiff",
"Alaskan Malamute",
"Dalmatian",
"Dogue de Bordeaux",
"Old English Sheepdog",
"Irish Setter",
"Greater Swiss Mountain Dog",
"Bouvier des Flandres",
"Anatolian Shepherd Dog",
"Afghan Hound",
"English Setter",
"Flat-Coated Retriever",
"Borzoi",
"Gordon Setter",
"Spinone Italiano",
"Black Russian Terrier",
"Belgian Sheepdog",
"Saluki",
"Boerboel",
"Briard",
"Black and Tan Coonhound",
"Bluetick Coonhound",
"Beauceron",
"Tibetan Mastiff",
"Irish Red and White Setter",
"Komondor",
"Ibizan Hound",
"Curly-Coated Retriever",
"Chinook",
"Bergamasco",
"Otterhound",
"American Foxhound",
"Sloughi",
"Grand Bleu de Gascogne",
"Kangal Dog",
"Spanish Greyhound",
"Akbash Dog",
"Alano Espanol",
"Alapaha Blue Blood Bulldog",
"American Mastiff",
"American Staghound",
"Argentine Dogo",
"Ariege Pointer",
"Azawakh",
"Blue Picardy Spaniel",
"Bracco Italiano",
"Bukovina Sheepdog",
"Bulgarian Shepherd Dog",
"Canadian Eskimo Dog",
"Caravan Hound",
"Carpathian Sheepdog",
"Caucasian Ovcharka",
"Central Asian Ovtcharka",
"Czechoslovakian Wolfdog",
"Dutch Shepherd Dog",
"East Siberian Laika",
"East-European Shepherd",
"Francais Blanc et Noir",
"German Longhaired Pointer",
"Greenland Dog",
"Large Munsterlander",
"Northern Inuit Dog",
"Perro de Presa Canario",
"Picardy Spaniel",
"Pudelpointer",
"Rajapalayam dog",
"Saarloos wolfdog",
"South Russian Ovcharka",
"Tamaskan Dog",
"Tornjak",
"Tosa Ken",
"West Siberian Laika",
"Alaskan Husky",
"American Bulldog",
"Bull Arab",
"Majestic Tree Hound",
"Maremma Sheepdog",
"Slovensky Cuvac",
"Moscow Watchdog",
"Mountain Cur",
"Polish Tatra Sheepdog",
"Great Dane", #giant
"Mastiff",
"Newfoundland",
"St. Bernard",
"Great Pyrenees",
"Irish Wolfhound",
"Giant Schnauzer",
"Leonberger",
"Neapolitan Mastiff",
"Greyhound",
"Kuvasz",
"Scottish Deerhound",
"Chart Polski",
"Landseer",
"Pakistani Mastiff",
"Shiloh Shepherd dog",
"Spanish Mastiff",
"King Shepherd"]

small = ["French Bulldog",
"Beagle",
"Yorkshire Terrier",
"Dachshund",
"Pembroke Welsh Corgi",
"Miniature Schnauzer",
"Cavalier King Charles Spaniel",
"Shih Tzu",
"Boston Terrier",
"Pomeranian",
"Havanese",
"Shetland Sheepdog",
"Pug",
"Chihuahua",
"Maltese",
"West Highland White Terrier",
"Bichon Frise",
"Papillon",
"Scottish Terrier",
"Cardigan Welsh Corgi",
"Cairn Terrier",
"Miniature Pinscher",
"Italian Greyhound",
"Lhasa Apso",
"Jack Russell Terrier",
"Chinese Crested",
"Coton De Tulear",
"Keeshond",
"Pekingese",
"Border Terrier",
"Brussels Griffon",
"Rat Terrier",
"Norwich Terrier",
"Silky Terrier",
"Japanese Chin",
"Welsh Terrier",
"Schipperke",
"Toy Fox Terrier",
"Irish Terrier",
"Miniature Bull Terrier",
"American Eskimo Dog",
"Parson Russell Terrier",
"Tibetan Spaniel",
"Smooth Fox Terrier",
"American Hairless Terrier",
"Norfolk Terrier",
"English Toy Spaniel",
"Manchester Terrier",
"Australian Terrier",
"Lakeland Terrier",
"Xoloitzcuintli",
"Affenpinscher",
"Swedish Vallhund",
"Sealyham Terrier",
"Bedlington Terrier",
"Glen of Imaal Terrier",
"Petit Basset Griffon Vendeen",
"Sussex Spaniel",
"Lowchen",
"Skye Terrier",
"Dandie Dinmont Terrier",
"Cesky Terrier",
"Norwegian Lundehund",
"Miniature Poodle",
"Toy Poodle",
"Miniature Shar Pei",
"Basset Bleu de Gascogne",
"Basset Fauve de Bretagne",
"Brazilian Terrier",
"Cockapoo",
"Danish-Swedish Farmdog",
"Drever",
"Dutch Smoushond",
"Jagdterrier",
"Goldendoodle",
"Japanese Spitz",
"Japanese Terrier",
"Lancashire Heeler",
"Miniature Bulldog",
"Patterdale Terrier",
"Plummer Terrier",
"Prazsky Krysarik",
"Russian Spaniel",
"Russian Toy",
"Karst Shepherd",
"Volpino Italiano",
"Alopekis",
"Basset Artesien Normand",
"Beaglier",
"Bolognese dog",
"Mountain Feist",
"Chizer",
"Cotonese",
"Taco Terrier",
"Cairmal",
"Kyi-Leo",
"Chorkie",
"Dorgi",
"Dorkie",
"Lucas Terrier",
"Mal-Shi",
"Shichon",
"Puggle",
"Russian Tsvetnaya Bolonka"]

medium = ["Labrador Retriever",
"Bulldog",
"Poodle",
"Boxer",
"Siberian Husky",
"Australian Shepherd",
"Brittany",
"English Springer Spaniel",
"American Cocker Spaniel",
"Vizsla",
"Weimaraner",
"Miniature American Shepherd",
"Border Collie",
"Basset Hound",
"Belgian Malinois",
"Shiba Inu",
"Soft Coated Wheaten Terrier",
"English Cocker Spaniel",
"Portuguese Water Dog",
"Airedale Terrier",
"Australian Cattle Dog",
"Samoyed",
"Bull Terrier",
"Whippet",
"German Wirehaired Pointer",
"Shar-Pei",
"Wirehaired Pointing Griffon",
"Chow Chow",
"Staffordshire Bull Terrier",
"American Staffordshire Terrier",
"Basenji",
"Nova Scotia Duck Tolling Retriever",
"Standard Schnauzer",
"Norwegian Elkhound",
"Boykin Spaniel",
"Wire Fox Terrier",
"Tibetan Terrier",
"Belgian Tervuren",
"Pointer",
"Lagotto Romagnolo",
"American Eskimo Dog",
"Bearded Collie",
"Kerry Blue Terrier",
"Treeing Walker Coonhound",
"Welsh Springer Spaniel",
"German Pinscher",
"Redbone Coonhound",
"Clumber Spaniel",
"Puli",
"Icelandic Sheepdog",
"Field Spaniel",
"Berger Picard",
"Spanish Water Dog",
"Entlebucher Mountain Dog",
"Wirehaired Vizsla",
"Portuguese Podengo Pequeno",
"Irish Water Spaniel",
"Plott Hound",
"American Water Spaniel",
"Norwegian Buhund",
"Finnish Lapphund",
"Pharaoh Hound",
"Canaan Dog",
"Polish Lowland Sheepdog",
"Finnish Spitz",
"American English Coonhound",
"Pyrenean Shepherd",
"Harrier",
"Cirneco dell’Etna",
"English Foxhound",
"Africanis",
"Aidi",
"Alaskan Klee Kai",
"American Pit Bull Terrier",
"American White Shepherd",
"Appenzeller Sennenhund",
"Ariegeois",
"Australian Bulldog",
"Australian Kelpie",
"Australian Stumpy Tail Cattle Dog",
"Austrian Black and Tan Hound",
"Austrian Pinscher",
"Barbet",
"Bavarian Mountain Hound",
"Belgian Shepherd Laekenois",
"Black Mouth Cur",
"Black Norwegian Elkhound",
"Blue Lacy",
"Bohemian Shepherd",
"Bouvier des Ardennes",
"Braque du Bourbonnais",
"Briquet Griffon Vendeen",
"Cão da Serra de Aires",
"Carolina Dog",
"Catahoula Bulldog",
"Catahoula Leopard Dog",
"Catalan Sheepdog",
"Cesky Fousek",
"Croatian Sheepdog",
"Deutsche Bracke",
"Dingo",
"Drentse Patrijshond",
"Dunker",
"English Shepherd",
"Eurasier",
"Fila Brasileiro",
"Finnish Hound",
"French Spaniel",
"Polish Hunting Dog",
"Grand Basset Griffon Vendeen",
"Griffon bleu de Gascogne",
"Hamilton Hound",
"Hokkaido Dog",
"Hovawart",
"Jämthund",
"Korean Jindo",
"Karelian Bear Dog",
"Kishu Ken",
"Kooikerhondje",
"Koolie",
"Kromfohrlander",
"Lapponian Herder",
"McNab",
"Mudi",
"Small Munsterlander",
"New Guinea Singing Dog",
"Norrbottenspets",
"Olde English Bulldogge",
"Perro de Presa Mallorquin",
"Peruvian Inca Orchid",
"Portuguese Pointer",
"Rafeiro do Alentejo",
"Sapsali",
"Sarplaninac",
"Schapendoes",
"Seppala Siberian Sleddog",
"Shikoku dog",
"Silken Windhound",
"Smaland Hound",
"Pont-Audemer Spaniel",
"Serbian Hound",
"Swedish Lapphund",
"Thai Bangkaew Dog",
"Thai Ridgeback",
"Transylvanian Hound",
"Wetterhoun",
"Andalusian Hound",
"Beagle-Harrier",
"Beaglier",
"Texas Heeler",
"Chippiparai",
"Cockalier",
"Double Doodle",
"Lurcher",
"Stabyhoun"]

large = ["German Shepherd",
"Golden Retriever",
"Rottweiler",
"German Shorthaired Pointer",
"Doberman Pinscher",
"Bernese Mountain Dog",
"Cane Corso",
"Collie",
"Rhodesian Ridgeback",
"Chesapeake Bay Retriever",
"Akita",
"Bloodhound",
"Bullmastiff",
"Alaskan Malamute",
"Dalmatian",
"Dogue de Bordeaux",
"Old English Sheepdog",
"Irish Setter",
"Greater Swiss Mountain Dog",
"Bouvier des Flandres",
"Anatolian Shepherd Dog",
"Afghan Hound",
"English Setter",
"Flat-Coated Retriever",
"Borzoi",
"Gordon Setter",
"Spinone Italiano",
"Black Russian Terrier",
"Belgian Sheepdog",
"Saluki",
"Boerboel",
"Briard",
"Black and Tan Coonhound",
"Bluetick Coonhound",
"Beauceron",
"Tibetan Mastiff",
"Irish Red and White Setter",
"Komondor",
"Ibizan Hound",
"Curly-Coated Retriever",
"Chinook",
"Bergamasco",
"Otterhound",
"American Foxhound",
"Sloughi",
"Grand Bleu de Gascogne",
"Kangal Dog",
"Spanish Greyhound",
"Akbash Dog",
"Alano Espanol",
"Alapaha Blue Blood Bulldog",
"American Mastiff",
"American Staghound",
"Argentine Dogo",
"Ariege Pointer",
"Azawakh",
"Blue Picardy Spaniel",
"Bracco Italiano",
"Bukovina Sheepdog",
"Bulgarian Shepherd Dog",
"Canadian Eskimo Dog",
"Caravan Hound",
"Carpathian Sheepdog",
"Caucasian Ovcharka",
"Central Asian Ovtcharka",
"Czechoslovakian Wolfdog",
"Dutch Shepherd Dog",
"East Siberian Laika",
"East-European Shepherd",
"Francais Blanc et Noir",
"German Longhaired Pointer",
"Greenland Dog",
"Large Munsterlander",
"Northern Inuit Dog",
"Perro de Presa Canario",
"Picardy Spaniel",
"Pudelpointer",
"Rajapalayam dog",
"Saarloos wolfdog",
"South Russian Ovcharka",
"Tamaskan Dog",
"Tornjak",
"Tosa Ken",
"West Siberian Laika",
"Alaskan Husky",
"American Bulldog",
"Bull Arab",
"Majestic Tree Hound",
"Maremma Sheepdog",
"Slovensky Cuvac",
"Moscow Watchdog",
"Mountain Cur",
"Polish Tatra Sheepdog"]

giant = ["Great Dane","Mastiff","Newfoundland","St. Bernard","Great Pyrenees","Irish Wolfhound","Giant Schnauzer","Leonberger",
"Neapolitan Mastiff","Greyhound","Kuvasz","Scottish Deerhound","Chart Polski","Landseer","Pakistani Mastiff","Shiloh Shepherd dog",
"Spanish Mastiff","King Shepherd"]

hypoallergenic = ["Poodle","Yorkshire Terrier","Miniature Schnauzer","Shih Tzu","Havanese","Maltese","West Highland White Terrier",
"Bichon Frise","Soft Coated Wheaten Terrier","Portuguese Water Dog","Airedale Terrier","Samoyed","Scottish Terrier","Wirehaired Pointing Griffon",
"Cairn Terrier","Italian Greyhound","Chinese Crested","Giant Schnauzer","Coton De Tulear","Bouvier des Flandres","Standard Schnauzer",
"Border Terrier","Afghan Hound","Brussels Griffon","Wire Fox Terrier","Tibetan Terrier","Norwich Terrier","Silky Terrier","Welsh Terrier",
"Irish Terrier","Lagotto Romagnolo","Norfolk Terrier","Kerry Blue Terrier","Australian Terrier","Lakeland Terrier","Puli","Xoloitzcuintli",
"Affenpinscher","Spanish Water Dog","Sealyham Terrier","Bedlington Terrier","Irish Water Spaniel","Lowchen","Polish Lowland Sheepdog",
"Bergamasco","Dandie Dinmont Terrier","Cesky Terrier","Toy Poodle","Barbet","Peruvian Inca Orchid","Bolognese dog","Kyi-Leo","Shichon",
"Mountain Cur","Russian Tsvetnaya Bolonka"]

fluffy = ["Poodle",
"Yorkshire Terrier",
"Shih Tzu",
"Pomeranian",
"Havanese",
"Shetland Sheepdog",
"Maltese",
"Newfoundland",
"Collie",
"Bichon Frise",
"Soft Coated Wheaten Terrier",
"Papillon",
"Samoyed",
"Cairn Terrier",
"Old English Sheepdog",
"Chow Chow",
"Lhasa Apso",
"Coton De Tulear",
"Bouvier des Flandres",
"Keeshond",
"Tibetan Terrier",
"Lagotto Romagnolo",
"American Eskimo Dog",
"Bearded Collie",
"Norfolk Terrier",
"Affenpinscher",
"Kuvasz",
"Glen of Imaal Terrier",
"Bergamasco",
"Miniature Poodle",
"Toy Poodle",
"Barbet",
"Cockapoo",
"Goldendoodle",
"Japanese Spitz",
"Volpino Italiano",
"Bolognese dog",
"Kyi-Leo",
"Lucas Terrier",
"Mal-Shi",
"Shichon",
"Slovensky Cuvac",
"Polish Tatra Sheepdog",
"Russian Tsvetnaya Bolonka"]
